name: Generate Delegation History

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install @hiveio/dhive dotenv

      - name: Run history generator
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}
        run: node scripts/generate_delegation_history.js

      - name: Upload generated file
        uses: actions/upload-artifact@v3
        with:
          name: delegation-history
          path: delegation_history.json
