name: Hive Payout

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 9:00 AM (Asia/Manila, which is UTC+8)
  workflow_dispatch:

jobs:
  payout:
    runs-on: ubuntu-22.04   # Use a specific Ubuntu version for consistency

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Initialize SQLite DB
        run: node scripts/init_db.js

      - name: Run payout script
        run: node scripts/payout.js
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}
          ACTIVE_KEY: ${{ secrets.ACTIVE_KEY }}
          DELEGATION_WEBHOOK_URL: ${{ secrets.DELEGATION_WEBHOOK_URL }}
