name: Hive Payout

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 9:00 AM Asia/Manila (UTC+8)
  workflow_dispatch:

permissions:
  contents: write  # Required to commit and push changes

jobs:
  payout:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Initialize database
        run: node scripts/init_db.js

      - name: Update delegation history
        run: node scripts/update_delegation_history.js
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}

      - name: Run payout script
        run: node scripts/payout.js
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}
          ACTIVE_KEY: ${{ secrets.ACTIVE_KEY }}
          DELEGATION_WEBHOOK_URL: ${{ secrets.DELEGATION_WEBHOOK_URL }}

      - name: Commit and push updated reward and log files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          FILES_TO_COMMIT=""

          if [ -f ui/reward_cache.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT ui/reward_cache.json"
          fi
          if [ -f ui/payout.log ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT ui/payout.log"
          fi
          if [ -f ui/curation_breakdown.log ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT ui/curation_breakdown.log"
          fi
          if [ -f delegation_snapshot.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT delegation_snapshot.json"
          fi
          if [ -f scripts/delegation_history.json ]; then
            FILES_TO_COMMIT="$FILES_TO_COMMIT scripts/delegation_history.json"
          fi

          if [ -n "$FILES_TO_COMMIT" ]; then
            git add $FILES_TO_COMMIT
            git commit -m "🤖 Update reward data and logs [auto]" || echo "No changes to commit"
            git push
          else
            echo "📭 No files to commit."
          fi
