name: Hive Payout

on:
  schedule:
    - cron: '0 1 * * *'  # Runs every day at 9:00 AM Asia/Manila (which is UTC+8)
  workflow_dispatch:

permissions:
  contents: write  # Allow commit/push

jobs:
  payout:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Initialize database
        run: node scripts/init_db.js

      - name: Run payout script
        run: node scripts/payout.js
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}
          ACTIVE_KEY: ${{ secrets.ACTIVE_KEY }}
          DELEGATION_WEBHOOK_URL: ${{ secrets.DELEGATION_WEBHOOK_URL }}

     - name: Commit and push updated reward and log files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Only add files if they exist
          if [ -f ui/reward_cache.json ]; then git add ui/reward_cache.json; fi
          if [ -f ui/payout.log ]; then git add ui/payout.log; fi
          if [ -f delegation_snapshot.json ]; then git add delegation_snapshot.json; fi
          if [ -f delegation_history.json ]; then git add delegation_history.json; fi

          git commit -m "🤖 Update reward data and logs [auto]" || echo "No changes to commit"
          git push
