name: Hive Payout with Dry Run

on:
  workflow_dispatch:

jobs:
  payout:
    runs-on: ubuntu-22.04

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧱 Initialize SQLite database
        run: node scripts/init_db.js

      - name: 💸 Run payout with DRY_RUN mode
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}
          ACTIVE_KEY: ${{ secrets.ACTIVE_KEY }}
          DELEGATION_WEBHOOK_URL: ${{ secrets.DELEGATION_WEBHOOK_URL }}
          DRY_RUN: true
        run: node scripts/payout.js
