name: Hive Tag to Discord

on:
  schedule:
    - cron: '*/2 * * * *'  # every 2 minutes
  workflow_dispatch:

permissions:
  contents: write  # 👈 required for pushing commits

jobs:
  notify:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tag-to-discord.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_TAG_BOT }}
        run: node scripts/tag-to-discord.js

      - name: Commit updated cache
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add scripts/latest_post.json
          git diff --cached --quiet || git commit -m "Update latest_post.json cache"
          git push
